#include "trustlineauthorizedtomaintainliabilitieseffectresponse.h"

TrustlineAuthorizedToMaintainLiabilitiesEffectResponse::TrustlineAuthorizedToMaintainLiabilitiesEffectResponse()
{

}

TrustlineAuthorizedToMaintainLiabilitiesEffectResponse::~TrustlineAuthorizedToMaintainLiabilitiesEffectResponse()
{

}
