#include "trustlineauthorizedtomaintainliabilitieseffectresponse.h"

QSTELLAR_BEGIN_NS


TrustlineAuthorizedToMaintainLiabilitiesEffectResponse::TrustlineAuthorizedToMaintainLiabilitiesEffectResponse()
{

}

TrustlineAuthorizedToMaintainLiabilitiesEffectResponse::~TrustlineAuthorizedToMaintainLiabilitiesEffectResponse()
{

}
QSTELLAR_END_NS
